env:
  global:
    - BUGZILLA_DEV_HOST="https://bugzilla-dev.allizom.org"
    - BUGZILLA_DEV_API_KEY=PcKr3LgH6bL0WDXlPuC0wLhFTUuhT8UJSvPKF0UQ
matrix:
    include:
        - language: go
          services:
            - docker
          go: stable
          install:
               # Handle forks by copying this checkout to the expected fork directory
               - mkdir -p ${GOPATH}/src/github.com/mozilla/OneCRL-Tools
               - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/mozilla/OneCRL-Tools/
                # Now install dependencies
               - go get -t ./...
          script:
              # Due to both the `kinto` package and the `ccadb2OneCRL` package wanting
              # to use docker-compose to have a test Kinto instance around we need to
              # run these tests sequentially or they will clobber each other (hence `-p 1`).
              # If you know how to easily get two Kintos running at the same time
              # without stepping over each others names/ports/anything else then please
              # do so and remove this `-p 1`.
              - go test -v -p 1 ./...
              - tests/integration.sh
        - language: rust
          rust: 1.39.0
          script:
              - cd one_crl_to_cert_storage
              - cargo build --verbose
