env:
  global:
    - BUGZILLA_DEV_HOST="https://bugzilla-dev.allizom.org"
    - BUGZILLA_DEV_API_KEY=PcKr3LgH6bL0WDXlPuC0wLhFTUuhT8UJSvPKF0UQ
matrix:
    include:
        - language: go
          go: stable
          install:
               # Handle forks by copying this checkout to the expected fork directory
               - mkdir -p ${GOPATH}/src/github.com/mozilla/OneCRL-Tools
               - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/mozilla/OneCRL-Tools/
                # Now install dependencies
               - go get -t ./...
          script:
              - go test -v ./...
              - tests/integration.sh
        - language: rust
          rust: 1.39.0
          script:
              - cd one_crl_to_cert_storage
              - cargo build --verbose


